---
version: "2.1"
services:
  nextcloud:
    image: ghcr.io/linuxserver/nextcloud:php8
    container_name: nextcloud
    environment:
      - PUID=1001
      - PGID=998
      - TZ=Asia/Singapore
      - NEXTCLOUD_ADMIN_USER=adamint
      - NEXTCLOUD_ADMIN_PASSWORD=Focused%Test8*
      - MYSQL_USER=nextcloud_user
      - MYSQL_PASSWORD=Total&Disaster5
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
    volumes:
      - /mnt/hdd/dockerstuff/nextcloud/config:/config
      - /mnt/hdd/dockerstuff/nextcloud/data:/data
    ports:
      - 443:443
    restart: unless-stopped
    depends_on:
      - mariadb
      - redis
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
  mariadb:
    image: ghcr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1001
      - PGID=998
      - TZ=Asia/Singapore
      - MYSQL_DATABASE=nextcloud 
      - MYSQL_USER=nextcloud_user
      - MYSQL_PASSWORD=Total&Disaster5
      - MYSQL_ROOT_PASSWORD=Not*Totaled8
    volumes:
      - /mnt/hdd/dockerstuff/mariadb:/config
    restart: unless-stopped